ALTER TABLE concepts ADD COLUMN ontology_layer VARCHAR(80) DEFAULT NULL;
ALTER TABLE concepts ADD COLUMN source_confidence ENUM('HIGH','LOW','MEDIUM') DEFAULT NULL;
ALTER TABLE concepts ADD COLUMN created_by VARCHAR(64) NOT NULL DEFAULT 'USER';
ALTER TABLE concepts ADD COLUMN tags_json LONGTEXT DEFAULT NULL;

ALTER TABLE knowledge_objects ADD COLUMN ontology_layer VARCHAR(80) DEFAULT NULL;
ALTER TABLE knowledge_objects ADD COLUMN source_confidence ENUM('HIGH','LOW','MEDIUM') DEFAULT NULL;
ALTER TABLE knowledge_objects ADD COLUMN created_by VARCHAR(64) NOT NULL DEFAULT 'USER';
