ALTER TABLE ai_interactions MODIFY COLUMN suggestion_type ENUM(
    'EXTRACT_ACTIONS',
    'EXTRACT_CONCEPTS',
    'FORUM_THREAD_DRAFT',
    'NOTE_SUMMARY',
    'SUGGEST_DESIGN_LENSES',
    'SUGGEST_PROJECT_APPLICATIONS'
) NOT NULL;

ALTER TABLE ai_suggestions MODIFY COLUMN suggestion_type ENUM(
    'EXTRACT_ACTIONS',
    'EXTRACT_CONCEPTS',
    'FORUM_THREAD_DRAFT',
    'NOTE_SUMMARY',
    'SUGGEST_DESIGN_LENSES',
    'SUGGEST_PROJECT_APPLICATIONS'
) NOT NULL;
