/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBadge: typeof import('./components/ui/AppBadge.vue')['default']
    AppButton: typeof import('./components/ui/AppButton.vue')['default']
    AppCard: typeof import('./components/ui/AppCard.vue')['default']
    AppDivider: typeof import('./components/ui/AppDivider.vue')['default']
    AppEmptyState: typeof import('./components/ui/AppEmptyState.vue')['default']
    AppErrorState: typeof import('./components/ui/AppErrorState.vue')['default']
    AppIconButton: typeof import('./components/ui/AppIconButton.vue')['default']
    AppLoadingState: typeof import('./components/ui/AppLoadingState.vue')['default']
    AppProgressBar: typeof import('./components/ui/AppProgressBar.vue')['default']
    AppSectionHeader: typeof import('./components/ui/AppSectionHeader.vue')['default']
    AppStat: typeof import('./components/ui/AppStat.vue')['default']
    AppTooltip: typeof import('./components/ui/AppTooltip.vue')['default']
    BookCaptureSection: typeof import('./components/book-detail/BookCaptureSection.vue')['default']
    BookCard: typeof import('./components/BookCard.vue')['default']
    BookContextHeader: typeof import('./components/book-detail/BookContextHeader.vue')['default']
    BookCover: typeof import('./components/book-detail/BookCover.vue')['default']
    BookFilterBar: typeof import('./components/BookFilterBar.vue')['default']
    BookFormPanel: typeof import('./components/BookFormPanel.vue')['default']
    BookHero: typeof import('./components/book-detail/BookHero.vue')['default']
    BookInsightCards: typeof import('./components/book-detail/BookInsightCards.vue')['default']
    BookKnowledgeSection: typeof import('./components/book-detail/BookKnowledgeSection.vue')['default']
    BookMetaStats: typeof import('./components/book-detail/BookMetaStats.vue')['default']
    BookProgressBar: typeof import('./components/BookProgressBar.vue')['default']
    BookRating: typeof import('./components/BookRating.vue')['default']
    BookStatusBadge: typeof import('./components/BookStatusBadge.vue')['default']
    BookTable: typeof import('./components/BookTable.vue')['default']
    ContextPanel: typeof import('./components/ContextPanel.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRate: typeof import('element-plus/es')['ElRate']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    FavoriteBookButton: typeof import('./components/book-detail/FavoriteBookButton.vue')['default']
    ReadingProgressBar: typeof import('./components/book-detail/ReadingProgressBar.vue')['default']
    RightRail: typeof import('./components/RightRail.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./components/Sidebar.vue')['default']
    TopNav: typeof import('./components/TopNav.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
